### ISSUE TITLE
use thrust for possible improvement

### ISSUE THREAD

**Issue by kwea123** [sunset1995/torch_efficient_distloss#4]
I didn't try on your code base, but `thrust` has a function to efficiently compute prefix sums: https://thrust.github.io/doc/group__prefixsums_ga7be5451c96d8f649c8c43208fcebb8c3.html

Maybe you can try this, it has complexity O(logN) instead of O(N)

**Comment by sunset1995** [comment]
Thanks for sharing!

But there are two problems block me from using the existing prefix sum libraries:
1. They don't support segment prefix sum while my array consists of multiple segmented sub-array.
2. A workaround is to compute prefix sum of whole array and then subtract the prefix sum of the previous segment. In this case, the complexity is `log(N) + log(M)` and the original is `M`. This workaround wouldn't gain speedup when `M` is small. Besides, the floating point precision could be a problem. For example:
```
N, M = 8192, 16
x = torch.nn.functional.normalize(torch.rand(N, M), p=1, dim=1).cuda()
x_cum = x.cumsum(1)
x_cum_flat = x.view(-1).cumsum(0).view(N, M)
x_cum_flat[1:] -= x_cum_flat[:-1, [-1]]
print((x_cum_flat - x_cum).abs())
```
The difference will be larger and larger as `N`, `M` increase.

**Comment by sxyu** [comment]
CUB has some segmented scan function which might be relevant:
https://nvlabs.github.io/cub/structcub_1_1_device_scan.html#a11698ce8ad1d8369081e833d07301c61
at::cuda::cub::inclusive_sum_by_key
